### ISSUE TITLE
Update markup of templates to Bootstrap 5

### ISSUE THREAD

**Issue by santonelli** [plone/plone.z3cform#15]
Due to #2967 we have to update icons and markup of the templates listed below. Feel free to add missing templates here.

Updated:

- [x] plone.z3cform.crud.crud-row.pt
- [x] plone.z3cform.crud.crud-table.pt

Unknown:

- [ ] plone.z3cform.crud.crud-add.pt
- [ ] plone.z3cform.crud.crud-master.pt
- [ ] plone.z3cform.pagetemplates.form.pt
- [ ] plone.z3cform.pagetemplates.layout.pt
- [ ] plone.z3cform.pagetemplates.macros.pt
- [ ] plone.z3cform.pagetemplates.subform.pt
- [ ] plone.z3cform.pagetemplates.wrappedform.pt
- [ ] plone.z3cform.pagetemplates.wrappedsubform.pt

**Comment by santonelli** [comment]
@petschki considered as done?

**Comment by petschki** [comment]
yes
