### ISSUE TITLE
package tests not running

### ISSUE THREAD

**Issue by petschki** [plone/plone.z3cform#4]
can someone with permission please enable this package on travis-ci? and the PR checks for jenkins aren't enabled too event though I've changed the repo url in buildout.coredev/source.cfg ...

/cc @plone/testing-team

**Comment by tisto** [comment]
@petschki activated.

**Comment by tisto** [comment]
@petschki can we do a release here?

**Comment by petschki** [comment]
@tisto a release would be great!
